// Subscription plans and trial settings
export const TRIAL_DURATION_DAYS = 14; // 14-day free trial

export const SUBSCRIPTION_PLANS = {
	// ========== CORE SUBSCRIPTION TIERS ==========
	HOME: {
		id: 'home',
		name: 'Home',
		priceMonthly: 0,
		priceYearly: 0,
		maxProperties: 1,
		maxDevices: 8,
		features: [
			'1 Property',
			'Up to 8 Devices & Systems',
			'Maintenance History Tracking',
			'Recurring Maintenance Scheduling',
			'Document & Photo Storage',
			'Maintenance Timeline',
			'Basic Search',
			'Notifications & Reminders',
		],
		permissions: {
			canManageTeam: false,
			canManageTenants: false,
			canViewReports: false,
			canExportData: false,
			canAdvancedAuditTrail: false,
			canManageMultiUnit: false,
			canTrackWarranties: false,
			canLinkParts: false,
			canPortfolioReporting: false,
			canAdvancedAnalytics: false,
			canPropertyGroups: false,
			prioritySupport: false,
			canCreateProperties: true,
			canManageProperties: true,
			canSubmitMaintenanceRequests: false,
			canViewTenantInfo: false,
		},
	},
	PROPERTY: {
		id: 'property',
		name: 'Property',
		priceMonthly: 9,
		priceYearly: 89,
		maxProperties: 3, // 2-3 included
		maxDevices: 999, // Unlimited
		features: [
			'Everything in Home, plus:',
			'Unlimited Devices & Systems',
			'Unlimited Maintenance Records',
			'Linked Parts & Supplies',
			'Advanced Document Storage',
			'Service History Timelines',
			'Recurring Care Automation',
			'Advanced Search & Retrieval',
			'Property Reports & Exports',
			'Warranty Tracking',
			'Expanded Storage',
			'Multiple Properties (2–3 Included)',
		],
		permissions: {
			canManageTeam: false,
			canManageTenants: false,
			canViewReports: true,
			canExportData: true,
			canAdvancedAuditTrail: true,
			canManageMultiUnit: false,
			canTrackWarranties: true,
			canLinkParts: true,
			canPortfolioReporting: false,
			canAdvancedAnalytics: false,
			canPropertyGroups: false,
			prioritySupport: false,
			canCreateProperties: true,
			canManageProperties: true,
			canSubmitMaintenanceRequests: false,
			canViewTenantInfo: false,
		},
	},
	PORTFOLIO: {
		id: 'portfolio',
		name: 'Portfolio',
		priceMonthly: 24,
		priceYearly: 249,
		maxProperties: 15,
		maxDevices: 999, // Unlimited
		features: [
			'Everything in Property, plus:',
			'Up to 15 Properties',
			'Team Collaboration',
			'Tenant Maintenance Requests',
			'Role-Based Access',
			'Maintenance Assignment Workflows',
			'Portfolio-Level Reporting',
			'Advanced Maintenance Analytics',
			'Property Groups',
			'Expanded Storage & History Retention',
		],
		permissions: {
			canManageTeam: true,
			canManageTenants: true,
			canViewReports: true,
			canExportData: true,
			canAdvancedAuditTrail: true,
			canManageMultiUnit: true,
			canTrackWarranties: true,
			canLinkParts: true,
			canPortfolioReporting: true,
			canAdvancedAnalytics: true,
			canPropertyGroups: true,
			prioritySupport: true,
			canCreateProperties: true,
			canManageProperties: true,
			canSubmitMaintenanceRequests: false,
			canViewTenantInfo: false,
		},
	},

	// ========== SPECIAL ROLES (Not subscription tiers) ==========
	GUEST: {
		id: 'guest',
		name: 'Guest',
		priceMonthly: 0,
		priceYearly: 0,
		maxProperties: 0, // Cannot create properties, only access shared ones
		maxDevices: 0,
		features: [
			'Access to shared properties only',
			'Cannot create new properties',
			'Limited to properties shared by others',
		],
		permissions: {
			canManageTeam: false,
			canManageTenants: false,
			canViewReports: false,
			canExportData: false,
			canAdvancedAuditTrail: false,
			canManageMultiUnit: false,
			canTrackWarranties: false,
			canLinkParts: false,
			canPortfolioReporting: false,
			canAdvancedAnalytics: false,
			canPropertyGroups: false,
			prioritySupport: false,
			canCreateProperties: false,
			canManageProperties: false,
			canSubmitMaintenanceRequests: false,
			canViewTenantInfo: false,
		},
	},
	TENANT: {
		id: 'tenant',
		name: 'Tenant',
		priceMonthly: 0,
		priceYearly: 0,
		maxProperties: 0, // Cannot create properties, only access assigned property/unit
		maxDevices: 0,
		features: [
			'Access to assigned property/unit only',
			'Cannot create or manage properties',
			'Submit maintenance requests',
			'View tenant information (read-only)',
		],
		permissions: {
			canManageTeam: false,
			canManageTenants: false,
			canViewReports: false,
			canExportData: false,
			canAdvancedAuditTrail: false,
			canManageMultiUnit: false,
			canTrackWarranties: false,
			canLinkParts: false,
			canPortfolioReporting: false,
			canAdvancedAnalytics: false,
			canPropertyGroups: false,
			prioritySupport: false,
			canCreateProperties: false,
			canManageProperties: false,
			canSubmitMaintenanceRequests: true,
			canViewTenantInfo: true,
		},
	},
};

export const SUBSCRIPTION_STATUS = {
	ACTIVE: 'active',
	TRIAL: 'trial',
	CANCELLED: 'cancelled',
	EXPIRED: 'expired',
	PAST_DUE: 'past_due',
} as const;

export type SubscriptionStatus =
	(typeof SUBSCRIPTION_STATUS)[keyof typeof SUBSCRIPTION_STATUS];
