// Subscription plans and legacy access-period settings
export const TRIAL_DURATION_DAYS = 14; // Legacy access-period duration

export const SUBSCRIPTION_PLANS = {
	// ========== CORE SUBSCRIPTION TIERS ==========
	HOMEOWNER: {
		id: 'homeowner',
		name: 'Homeowner',
		priceMonthly: 0,
		priceYearly: 0,
		maxProperties: 1,
		maxDevices: 15,
		maxFiles: 10,
		maxStorageGb: 1,
		features: [
			'1 Property',
			'Up to 15 Appliances & Systems',
			'Property Setup Assistant',
			'Manual Maintenance Tasks',
			'Maintenance History Tracking',
			'Suggested Maintenance Opportunities',
			'Maintenance Timeline',
			'Maintenance Exports',
			'Warranty Information',
			'Basic Search',
		],
		permissions: {
			canManageTeam: false,
			canManageTenants: false,
			canViewReports: true,
			canExportData: true,
			canAdvancedAuditTrail: false,
			canManageMultiUnit: false,
			canTrackWarranties: true,
			canLinkParts: false,
			canPortfolioReporting: false,
			canAdvancedAnalytics: false,
			canPropertyGroups: false,
			prioritySupport: false,
			canCreateProperties: true,
			canManageProperties: true,
			canSubmitMaintenanceRequests: false,
			canViewTenantInfo: false,
			canUseSuggestedMaintenancePackages: false,
			suggestedMaintenancePackageLimit: 0,
			canUseRecurringTasks: false,
			canUseNotifications: false,
		},
	},
	HOMEOWNER_PLUS: {
		id: 'homeowner_plus',
		name: 'Homeowner+',
		priceMonthly: 3.99,
		priceYearly: 39.99,
		maxProperties: 1,
		maxDevices: 999, // Unlimited
		maxFiles: 250,
		maxStorageGb: 5,
		features: [
			'Everything in Home, plus:',
			'Unlimited Appliances & Systems',
			'All Suggested Maintenance Packages',
			'Recurring Maintenance Tasks',
			'Notifications & Reminders',
			'Advanced Document Storage',
			'Service History Timelines',
			'Maintenance Exports',
			'Warranty Tracking',
			'Advanced Search & Retrieval',
		],
		permissions: {
			canManageTeam: false,
			canManageTenants: false,
			canViewReports: true,
			canExportData: true,
			canAdvancedAuditTrail: true,
			canManageMultiUnit: false,
			canTrackWarranties: true,
			canLinkParts: true,
			canPortfolioReporting: false,
			canAdvancedAnalytics: false,
			canPropertyGroups: false,
			prioritySupport: false,
			canCreateProperties: true,
			canManageProperties: true,
			canSubmitMaintenanceRequests: false,
			canViewTenantInfo: false,
			canUseSuggestedMaintenancePackages: true,
			suggestedMaintenancePackageLimit: 999,
			canUseRecurringTasks: true,
			canUseNotifications: true,
		},
	},
	PROPERTY: {
		id: 'property',
		name: 'Property',
		priceMonthly: 8.99,
		priceYearly: 89,
		maxProperties: 7,
		maxDevices: 999, // Unlimited
		maxFiles: 1500,
		maxStorageGb: 15,
		features: [
			'Everything in Homeowner+, plus:',
			'Unlimited Appliances & Systems',
			'All Suggested Maintenance Packages',
			'Recurring Maintenance Tasks',
			'Notifications & Reminders',
			'Unlimited Maintenance Records',
			'Linked Parts & Supplies',
			'Advanced Document Storage',
			'Service History Timelines',
			'Recurring Care Automation',
			'Advanced Search & Retrieval',
			'Property Reports & Exports',
			'Warranty Tracking',
			'Expanded Storage',
			'Up to 7 Properties',
			'Simple Team Management',
			'Property Groups',
			'Resident Profiles & Requests',
		],
		permissions: {
			canManageTeam: true,
			canManageTenants: true,
			canViewReports: true,
			canExportData: true,
			canAdvancedAuditTrail: true,
			canManageMultiUnit: false,
			canTrackWarranties: true,
			canLinkParts: true,
			canPortfolioReporting: false,
			canAdvancedAnalytics: false,
			canPropertyGroups: true,
			prioritySupport: false,
			canCreateProperties: true,
			canManageProperties: true,
			canSubmitMaintenanceRequests: false,
			canViewTenantInfo: true,
			canUseSuggestedMaintenancePackages: true,
			suggestedMaintenancePackageLimit: 999,
			canUseRecurringTasks: true,
			canUseNotifications: true,
		},
	},
	PORTFOLIO: {
		id: 'portfolio',
		name: 'Portfolio',
		priceMonthly: 23.99,
		priceYearly: 249,
		maxProperties: 15,
		maxDevices: 999, // Unlimited
		maxFiles: 5000,
		maxStorageGb: 25,
		features: [
			'Everything in Property, plus:',
			'Up to 15 Properties',
			'Team Collaboration',
			'Resident Maintenance Requests',
			'Role-Based Access',
			'Maintenance Assignment Tasks',
			'Portfolio-Level Reporting',
			'Advanced Maintenance Analytics',
			'Property Groups',
			'Expanded Storage & History Retention',
		],
		permissions: {
			canManageTeam: true,
			canManageTenants: true,
			canViewReports: true,
			canExportData: true,
			canAdvancedAuditTrail: true,
			canManageMultiUnit: true,
			canTrackWarranties: true,
			canLinkParts: true,
			canPortfolioReporting: true,
			canAdvancedAnalytics: true,
			canPropertyGroups: true,
			prioritySupport: true,
			canCreateProperties: true,
			canManageProperties: true,
			canSubmitMaintenanceRequests: false,
			canViewTenantInfo: true,
			canUseSuggestedMaintenancePackages: true,
			suggestedMaintenancePackageLimit: 999,
			canUseRecurringTasks: true,
			canUseNotifications: true,
		},
	},

	// ========== SPECIAL ROLES (Not subscription tiers) ==========
	GUEST: {
		id: 'guest',
		name: 'Guest',
		priceMonthly: 0,
		priceYearly: 0,
		maxProperties: 0, // Cannot create properties, only access shared ones
		maxDevices: 0,
		maxFiles: 0,
		maxStorageGb: 0,
		features: [
			'Access to shared properties only',
			'Cannot create new properties',
			'Limited to properties shared by others',
		],
		permissions: {
			canManageTeam: false,
			canManageTenants: false,
			canViewReports: false,
			canExportData: false,
			canAdvancedAuditTrail: false,
			canManageMultiUnit: false,
			canTrackWarranties: false,
			canLinkParts: false,
			canPortfolioReporting: false,
			canAdvancedAnalytics: false,
			canPropertyGroups: false,
			prioritySupport: false,
			canCreateProperties: false,
			canManageProperties: false,
			canSubmitMaintenanceRequests: false,
			canViewTenantInfo: false,
			canUseSuggestedMaintenancePackages: false,
			suggestedMaintenancePackageLimit: 0,
			canUseRecurringTasks: false,
			canUseNotifications: false,
		},
	},
	TEAM: {
		id: 'team',
		name: 'Team',
		priceMonthly: 0,
		priceYearly: 0,
		maxProperties: 0, // Uses access granted by the owning account
		maxDevices: 0,
		maxFiles: 0,
		maxStorageGb: 0,
		features: [
			'Access through an invited business account',
			'Cannot create or own subscriptions',
			'Uses the account owner plan limits',
		],
		permissions: {
			canManageTeam: false,
			canManageTenants: false,
			canViewReports: false,
			canExportData: false,
			canAdvancedAuditTrail: false,
			canManageMultiUnit: false,
			canTrackWarranties: false,
			canLinkParts: false,
			canPortfolioReporting: false,
			canAdvancedAnalytics: false,
			canPropertyGroups: false,
			prioritySupport: false,
			canCreateProperties: false,
			canManageProperties: false,
			canSubmitMaintenanceRequests: false,
			canViewTenantInfo: false,
			canUseSuggestedMaintenancePackages: false,
			suggestedMaintenancePackageLimit: 0,
			canUseRecurringTasks: false,
			canUseNotifications: false,
		},
	},
	TENANT: {
		id: 'tenant',
		name: 'Tenant',
		priceMonthly: 0,
		priceYearly: 0,
		maxProperties: 0, // Cannot create properties, only access assigned property
		maxDevices: 0,
		maxFiles: 0,
		maxStorageGb: 0,
		features: [
			'Access to assigned property only',
			'Cannot create or manage properties',
			'Submit maintenance requests',
			'View tenant information (read-only)',
		],
		permissions: {
			canManageTeam: false,
			canManageTenants: false,
			canViewReports: false,
			canExportData: false,
			canAdvancedAuditTrail: false,
			canManageMultiUnit: false,
			canTrackWarranties: false,
			canLinkParts: false,
			canPortfolioReporting: false,
			canAdvancedAnalytics: false,
			canPropertyGroups: false,
			prioritySupport: false,
			canCreateProperties: false,
			canManageProperties: false,
			canSubmitMaintenanceRequests: true,
			canViewTenantInfo: true,
			canUseSuggestedMaintenancePackages: false,
			suggestedMaintenancePackageLimit: 0,
			canUseRecurringTasks: false,
			canUseNotifications: false,
		},
	},
};

export const SUBSCRIPTION_STATUS = {
	ACTIVE: 'active',
	TRIAL: 'trial',
	CANCELLED: 'cancelled',
	EXPIRED: 'expired',
	PAST_DUE: 'past_due',
} as const;

export type SubscriptionStatus =
	(typeof SUBSCRIPTION_STATUS)[keyof typeof SUBSCRIPTION_STATUS];
