import type { PartKnowledgeDefinition } from 'propertyKnowledge/partKnowledgeCatalog';


export const HVAC_PART_KNOWLEDGE_CATALOG: PartKnowledgeDefinition[] = [
    {
		id: 'thermostat',
		label: 'Thermostat',
		category: 'accessory',
		relatedAssetTypes: ['hvac', 'heat_pump', 'furnace', 'central_ac', 'mini_split'],
		matchTerms: ['thermostat', 'smart thermostat', 'honeywell t6', 'ecobee', 'nest'],
		commonFields: ['brand', 'model', 'installDate', 'warranty'],
		defaultTarget: 'part',
	},
	{
		id: 'capacitor',
		label: 'Capacitor',
		category: 'part',
		relatedAssetTypes: ['hvac', 'heat_pump', 'central_ac'],
		matchTerms: ['capacitor', 'run capacitor', 'start capacitor'],
		commonFields: ['partNumber', 'rating'],
		defaultTarget: 'part',
	},
	{
		id: 'air_filter',
		label: 'Air filter',
		category: 'consumable',
		relatedAssetTypes: ['hvac', 'heat_pump', 'furnace', 'central_ac'],
		matchTerms: ['air filter', 'hvac filter', 'furnace filter', 'return filter'],
		commonFields: ['size', 'mervRating', 'replacementInterval'],
		defaultTarget: 'part',
	},
	{
		id: 'refrigerant',
		label: 'Refrigerant',
		category: 'supply',
		relatedAssetTypes: ['hvac', 'heat_pump', 'central_ac', 'mini_split'],
		matchTerms: ['refrigerant', 'r-410a', 'r410a', 'r-22', 'r22', 'r-32', 'r32'],
		commonFields: ['type'],
		defaultTarget: 'part',
	},
	{
		id: 'drain_pan',
		label: 'Drain pan',
		category: 'part',
		relatedAssetTypes: ['hvac', 'heat_pump', 'central_ac', 'furnace'],
		matchTerms: ['drain pan', 'condensate pan'],
		commonFields: ['size', 'material'],
		defaultTarget: 'part',
	},
	{
		id: 'safety_switch',
		label: 'Safety switch',
		category: 'part',
		relatedAssetTypes: ['hvac', 'heat_pump', 'central_ac', 'furnace'],
		matchTerms: ['safety switch', 'float switch', 'overflow switch'],
		commonFields: ['partNumber'],
		defaultTarget: 'part',
	},
	{
		id: 'disconnect_box',
		label: 'Disconnect box',
		category: 'accessory',
		relatedAssetTypes: ['hvac', 'heat_pump', 'central_ac', 'mini_split'],
		matchTerms: ['disconnect box', 'ac disconnect', 'service disconnect'],
		commonFields: ['voltage'],
		defaultTarget: 'part',
	},
	{
		id: 'contactor',
		label: 'Contactor',
		category: 'part',
		relatedAssetTypes: ['hvac', 'heat_pump', 'central_ac'],
		matchTerms: ['contactor', 'compressor contactor'],
		commonFields: ['partNumber', 'voltage'],
		defaultTarget: 'part',
	},
	{
		id: 'blower_motor',
		label: 'Blower motor',
		category: 'part',
		relatedAssetTypes: ['hvac', 'heat_pump', 'furnace', 'central_ac'],
		matchTerms: ['blower motor', 'fan motor', 'ecm motor'],
		commonFields: ['partNumber', 'voltage'],
		defaultTarget: 'part',
	},
	{
		id: 'condensate_pump',
		label: 'Condensate pump',
		category: 'part',
		relatedAssetTypes: ['hvac', 'heat_pump', 'furnace', 'central_ac'],
		matchTerms: ['condensate pump', 'condensation pump'],
		commonFields: ['partNumber'],
		defaultTarget: 'part',
	},
	{
		id: 'coil',
		label: 'Coil',
		category: 'part',
		relatedAssetTypes: ['hvac', 'heat_pump', 'central_ac'],
		matchTerms: ['coil', 'evaporator coil', 'multi-position coil'],
		commonFields: ['model', 'partNumber'],
		defaultTarget: 'part',
	},
	{
		id: 'condenser',
		label: 'Condenser',
		category: 'part',
		relatedAssetTypes: ['hvac', 'heat_pump', 'central_ac'],
		matchTerms: ['condenser', 'heat pump condenser', 'ac condenser'],
		commonFields: ['model', 'partNumber'],
		defaultTarget: 'part',
	},
];
