"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sendAccessLifecycleActivationOnGrantCreate = exports.redeemComplimentaryAccessCode = exports.previewComplimentaryAccessCode = exports.releaseStorageQuotaUsage = exports.finalizeStorageQuotaUsage = exports.getStorageQuotaStatus = exports.reserveStorageUpload = exports.manageManualOccupancy = exports.manageRecurringTask = exports.activatePropertySetupMaintenancePlan = exports.issueHomeownerPlusTrialOnFirstProperty = exports.finalizeFirstPropertyTrial = exports.recordUserActivity = exports.ensureFamilyAccount = exports.updateFamilyMember = exports.updateFamilyMemberRole = exports.acceptFamilyInvite = exports.revokeFamilyInvite = exports.listFamilyInvites = exports.createFamilyInvite = exports.getFamilyMembers = exports.resendFamilyMemberInvite = exports.deletePropertyGroupCascade = exports.deletePropertyCascade = exports.deleteFamilyMemberAccount = exports.deleteUserAccount = exports.enforceEmailPreferences = exports.debugOverdueTasks = exports.sendWelcomeSignupEmail = exports.sendTeamMemberTaskReports = exports.sendTaskReminderEmails = exports.sendSeasonalGuidanceEmailTest = exports.sendSeasonalGuidanceEmails = exports.sendMonthlyPropertyInsightsTest = exports.sendMonthlyPropertyInsights = exports.sendMonthlyPropertySummaryTest = exports.sendMonthlyPropertySummaries = exports.markTasksAsOverdue = exports.listMyFeedbackTickets = exports.submitFeedback = exports.createTrialSubscription = exports.stripeWebhook = exports.syncSubscriptionFromStripe = exports.getSubscriptionDetails = exports.cancelSubscription = exports.verifyCheckoutSession = exports.validatePromotionCode = exports.createCheckoutSession = exports.publishMaintleyEvent = exports.sendPushOnNotificationCreate = void 0;
exports.cleanupTaskSpaceLinks = exports.cleanupEquipmentSpaceLinks = exports.personalAssistantApi = exports.managePersonalAssistantCredentials = exports.adminPortalMutateMaintleyTeam = exports.adminPortalListMaintleyTeam = exports.cleanupClosedFeedbackAttachments = exports.deleteFeedbackAdminParentTicket = exports.unlinkFeedbackAdminTicket = exports.linkFeedbackAdminTickets = exports.updateFeedbackAdminTicketStatus = exports.adminPortalCreateCheckoutLinkWithCoupon = exports.adminPortalListBillingCoupons = exports.adminPortalCreateBillingCoupon = exports.adminPortalListComplimentaryAccessCodes = exports.adminPortalCreateComplimentaryAccessCode = exports.adminPortalApplyUserBillingActions = exports.adminPortalRefreshUserSubscriptionFromStripe = exports.adminPortalManageUserSubscription = exports.adminPortalMutateEntitlementGrant = exports.adminPortalPreviewEntitlementGrant = exports.getAdminPortalUserTroubleshootingDetails = exports.listAdminPortalAuditLogs = exports.listAdminPortalUsers = exports.listFeedbackAdminTickets = exports.adminPortalResetPassword = exports.adminPortalLogout = exports.validateAdminPortalSession = exports.adminPortalLogin = exports.syncTenantAccessFromInvites = exports.redeemTenantInvitationCode = exports.revokeTenantInvitationCode = exports.createTenantInvitationCode = exports.validateTenantInvitationCode = exports.redeemTeamMemberInvitationCode = exports.revokeTeamMemberInvitationCode = exports.validateTeamMemberInvitationCode = exports.createTeamMemberInvitationCode = exports.processPropertyDocumentAcquisitionRequests = exports.processPropertyDocumentAcquisition = exports.notifyTaskCompletion = exports.correctMaintenanceHistoryRecord = exports.deleteMaintenanceEvent = exports.updateMaintenanceEvent = exports.createMaintenanceEventsBatch = exports.createMaintenanceEvent = exports.sendAdminOperationalUserEmail = exports.sendAdminAccessLifecycleEmail = exports.sendAccessLifecycleEmailTest = exports.sendAccessLifecycleEmails = void 0;
exports.setTaskSpaceLinks = exports.setEquipmentSpaceLinks = exports.removePropertySpace = void 0;
var sendPushOnNotificationCreate_1 = require("./sendPushOnNotificationCreate");
Object.defineProperty(exports, "sendPushOnNotificationCreate", { enumerable: true, get: function () { return sendPushOnNotificationCreate_1.sendPushOnNotificationCreate; } });
var maintleyEventEngine_1 = require("./maintleyEventEngine");
Object.defineProperty(exports, "publishMaintleyEvent", { enumerable: true, get: function () { return maintleyEventEngine_1.publishMaintleyEvent; } });
var stripeFunctions_1 = require("./stripeFunctions");
Object.defineProperty(exports, "createCheckoutSession", { enumerable: true, get: function () { return stripeFunctions_1.createCheckoutSession; } });
Object.defineProperty(exports, "validatePromotionCode", { enumerable: true, get: function () { return stripeFunctions_1.validatePromotionCode; } });
Object.defineProperty(exports, "verifyCheckoutSession", { enumerable: true, get: function () { return stripeFunctions_1.verifyCheckoutSession; } });
Object.defineProperty(exports, "cancelSubscription", { enumerable: true, get: function () { return stripeFunctions_1.cancelSubscription; } });
Object.defineProperty(exports, "getSubscriptionDetails", { enumerable: true, get: function () { return stripeFunctions_1.getSubscriptionDetails; } });
Object.defineProperty(exports, "syncSubscriptionFromStripe", { enumerable: true, get: function () { return stripeFunctions_1.syncSubscriptionFromStripe; } });
Object.defineProperty(exports, "stripeWebhook", { enumerable: true, get: function () { return stripeFunctions_1.stripeWebhook; } });
Object.defineProperty(exports, "createTrialSubscription", { enumerable: true, get: function () { return stripeFunctions_1.createTrialSubscription; } });
// Centralized server-side feedback + email handling path.
var submitFeedback_1 = require("./submitFeedback");
Object.defineProperty(exports, "submitFeedback", { enumerable: true, get: function () { return submitFeedback_1.submitFeedback; } });
Object.defineProperty(exports, "listMyFeedbackTickets", { enumerable: true, get: function () { return submitFeedback_1.listMyFeedbackTickets; } });
var markTasksAsOverdue_1 = require("./markTasksAsOverdue");
Object.defineProperty(exports, "markTasksAsOverdue", { enumerable: true, get: function () { return markTasksAsOverdue_1.markTasksAsOverdue; } });
var monthlyPropertySummary_1 = require("./monthlyPropertySummary");
Object.defineProperty(exports, "sendMonthlyPropertySummaries", { enumerable: true, get: function () { return monthlyPropertySummary_1.sendMonthlyPropertySummaries; } });
Object.defineProperty(exports, "sendMonthlyPropertySummaryTest", { enumerable: true, get: function () { return monthlyPropertySummary_1.sendMonthlyPropertySummaryTest; } });
var propertyInsightEmails_1 = require("./propertyInsightEmails");
Object.defineProperty(exports, "sendMonthlyPropertyInsights", { enumerable: true, get: function () { return propertyInsightEmails_1.sendMonthlyPropertyInsights; } });
Object.defineProperty(exports, "sendMonthlyPropertyInsightsTest", { enumerable: true, get: function () { return propertyInsightEmails_1.sendMonthlyPropertyInsightsTest; } });
var seasonalGuidanceEmails_1 = require("./seasonalGuidanceEmails");
Object.defineProperty(exports, "sendSeasonalGuidanceEmails", { enumerable: true, get: function () { return seasonalGuidanceEmails_1.sendSeasonalGuidanceEmails; } });
Object.defineProperty(exports, "sendSeasonalGuidanceEmailTest", { enumerable: true, get: function () { return seasonalGuidanceEmails_1.sendSeasonalGuidanceEmailTest; } });
var taskReminderEmails_1 = require("./taskReminderEmails");
Object.defineProperty(exports, "sendTaskReminderEmails", { enumerable: true, get: function () { return taskReminderEmails_1.sendTaskReminderEmails; } });
var teamMemberTaskReports_1 = require("./teamMemberTaskReports");
Object.defineProperty(exports, "sendTeamMemberTaskReports", { enumerable: true, get: function () { return teamMemberTaskReports_1.sendTeamMemberTaskReports; } });
var welcomeSignupEmail_1 = require("./welcomeSignupEmail");
Object.defineProperty(exports, "sendWelcomeSignupEmail", { enumerable: true, get: function () { return welcomeSignupEmail_1.sendWelcomeSignupEmail; } });
var debugOverdueTasks_1 = require("./debugOverdueTasks");
Object.defineProperty(exports, "debugOverdueTasks", { enumerable: true, get: function () { return debugOverdueTasks_1.debugOverdueTasks; } });
var enforceEmailPreferences_1 = require("./enforceEmailPreferences");
Object.defineProperty(exports, "enforceEmailPreferences", { enumerable: true, get: function () { return enforceEmailPreferences_1.enforceEmailPreferences; } });
var deleteUserAccount_1 = require("./deleteUserAccount");
Object.defineProperty(exports, "deleteUserAccount", { enumerable: true, get: function () { return deleteUserAccount_1.deleteUserAccount; } });
var deleteFamilyMemberAccount_1 = require("./deleteFamilyMemberAccount");
Object.defineProperty(exports, "deleteFamilyMemberAccount", { enumerable: true, get: function () { return deleteFamilyMemberAccount_1.deleteFamilyMemberAccount; } });
var deletePropertyCascade_1 = require("./deletePropertyCascade");
Object.defineProperty(exports, "deletePropertyCascade", { enumerable: true, get: function () { return deletePropertyCascade_1.deletePropertyCascade; } });
var deletePropertyGroupCascade_1 = require("./deletePropertyGroupCascade");
Object.defineProperty(exports, "deletePropertyGroupCascade", { enumerable: true, get: function () { return deletePropertyGroupCascade_1.deletePropertyGroupCascade; } });
var resendFamilyMemberInvite_1 = require("./resendFamilyMemberInvite");
Object.defineProperty(exports, "resendFamilyMemberInvite", { enumerable: true, get: function () { return resendFamilyMemberInvite_1.resendFamilyMemberInvite; } });
var getFamilyMembers_1 = require("./getFamilyMembers");
Object.defineProperty(exports, "getFamilyMembers", { enumerable: true, get: function () { return getFamilyMembers_1.getFamilyMembers; } });
var createFamilyInvite_1 = require("./createFamilyInvite");
Object.defineProperty(exports, "createFamilyInvite", { enumerable: true, get: function () { return createFamilyInvite_1.createFamilyInvite; } });
var listFamilyInvites_1 = require("./listFamilyInvites");
Object.defineProperty(exports, "listFamilyInvites", { enumerable: true, get: function () { return listFamilyInvites_1.listFamilyInvites; } });
var revokeFamilyInvite_1 = require("./revokeFamilyInvite");
Object.defineProperty(exports, "revokeFamilyInvite", { enumerable: true, get: function () { return revokeFamilyInvite_1.revokeFamilyInvite; } });
var acceptFamilyInvite_1 = require("./acceptFamilyInvite");
Object.defineProperty(exports, "acceptFamilyInvite", { enumerable: true, get: function () { return acceptFamilyInvite_1.acceptFamilyInvite; } });
var updateFamilyMemberRole_1 = require("./updateFamilyMemberRole");
Object.defineProperty(exports, "updateFamilyMemberRole", { enumerable: true, get: function () { return updateFamilyMemberRole_1.updateFamilyMemberRole; } });
var updateFamilyMember_1 = require("./updateFamilyMember");
Object.defineProperty(exports, "updateFamilyMember", { enumerable: true, get: function () { return updateFamilyMember_1.updateFamilyMember; } });
var ensureFamilyAccount_1 = require("./ensureFamilyAccount");
Object.defineProperty(exports, "ensureFamilyAccount", { enumerable: true, get: function () { return ensureFamilyAccount_1.ensureFamilyAccount; } });
var recordUserActivity_1 = require("./recordUserActivity");
Object.defineProperty(exports, "recordUserActivity", { enumerable: true, get: function () { return recordUserActivity_1.recordUserActivity; } });
var entitlementGrants_1 = require("./entitlementGrants");
Object.defineProperty(exports, "finalizeFirstPropertyTrial", { enumerable: true, get: function () { return entitlementGrants_1.finalizeFirstPropertyTrial; } });
Object.defineProperty(exports, "issueHomeownerPlusTrialOnFirstProperty", { enumerable: true, get: function () { return entitlementGrants_1.issueHomeownerPlusTrialOnFirstProperty; } });
var activatePropertySetupMaintenancePlan_1 = require("./activatePropertySetupMaintenancePlan");
Object.defineProperty(exports, "activatePropertySetupMaintenancePlan", { enumerable: true, get: function () { return activatePropertySetupMaintenancePlan_1.activatePropertySetupMaintenancePlan; } });
var manageRecurringTask_1 = require("./manageRecurringTask");
Object.defineProperty(exports, "manageRecurringTask", { enumerable: true, get: function () { return manageRecurringTask_1.manageRecurringTask; } });
var manageManualOccupancy_1 = require("./manageManualOccupancy");
Object.defineProperty(exports, "manageManualOccupancy", { enumerable: true, get: function () { return manageManualOccupancy_1.manageManualOccupancy; } });
var storageQuota_1 = require("./storageQuota");
Object.defineProperty(exports, "reserveStorageUpload", { enumerable: true, get: function () { return storageQuota_1.reserveStorageUpload; } });
Object.defineProperty(exports, "getStorageQuotaStatus", { enumerable: true, get: function () { return storageQuota_1.getStorageQuotaStatus; } });
Object.defineProperty(exports, "finalizeStorageQuotaUsage", { enumerable: true, get: function () { return storageQuota_1.finalizeStorageQuotaUsage; } });
Object.defineProperty(exports, "releaseStorageQuotaUsage", { enumerable: true, get: function () { return storageQuota_1.releaseStorageQuotaUsage; } });
var complimentaryAccessCodes_1 = require("./complimentaryAccessCodes");
Object.defineProperty(exports, "previewComplimentaryAccessCode", { enumerable: true, get: function () { return complimentaryAccessCodes_1.previewComplimentaryAccessCode; } });
Object.defineProperty(exports, "redeemComplimentaryAccessCode", { enumerable: true, get: function () { return complimentaryAccessCodes_1.redeemComplimentaryAccessCode; } });
var accessLifecycleEmails_1 = require("./accessLifecycleEmails");
Object.defineProperty(exports, "sendAccessLifecycleActivationOnGrantCreate", { enumerable: true, get: function () { return accessLifecycleEmails_1.sendAccessLifecycleActivationOnGrantCreate; } });
Object.defineProperty(exports, "sendAccessLifecycleEmails", { enumerable: true, get: function () { return accessLifecycleEmails_1.sendAccessLifecycleEmails; } });
Object.defineProperty(exports, "sendAccessLifecycleEmailTest", { enumerable: true, get: function () { return accessLifecycleEmails_1.sendAccessLifecycleEmailTest; } });
Object.defineProperty(exports, "sendAdminAccessLifecycleEmail", { enumerable: true, get: function () { return accessLifecycleEmails_1.sendAdminAccessLifecycleEmail; } });
Object.defineProperty(exports, "sendAdminOperationalUserEmail", { enumerable: true, get: function () { return accessLifecycleEmails_1.sendAdminOperationalUserEmail; } });
var maintenanceEvents_1 = require("./maintenanceEvents");
Object.defineProperty(exports, "createMaintenanceEvent", { enumerable: true, get: function () { return maintenanceEvents_1.createMaintenanceEvent; } });
Object.defineProperty(exports, "createMaintenanceEventsBatch", { enumerable: true, get: function () { return maintenanceEvents_1.createMaintenanceEventsBatch; } });
Object.defineProperty(exports, "updateMaintenanceEvent", { enumerable: true, get: function () { return maintenanceEvents_1.updateMaintenanceEvent; } });
Object.defineProperty(exports, "deleteMaintenanceEvent", { enumerable: true, get: function () { return maintenanceEvents_1.deleteMaintenanceEvent; } });
Object.defineProperty(exports, "correctMaintenanceHistoryRecord", { enumerable: true, get: function () { return maintenanceEvents_1.correctMaintenanceHistoryRecord; } });
Object.defineProperty(exports, "notifyTaskCompletion", { enumerable: true, get: function () { return maintenanceEvents_1.notifyTaskCompletion; } });
var propertyKnowledgeAcquisition_1 = require("./propertyKnowledgeAcquisition");
Object.defineProperty(exports, "processPropertyDocumentAcquisition", { enumerable: true, get: function () { return propertyKnowledgeAcquisition_1.processPropertyDocumentAcquisition; } });
Object.defineProperty(exports, "processPropertyDocumentAcquisitionRequests", { enumerable: true, get: function () { return propertyKnowledgeAcquisition_1.processPropertyDocumentAcquisitionRequests; } });
var teamInviteFunctions_1 = require("./teamInviteFunctions");
Object.defineProperty(exports, "createTeamMemberInvitationCode", { enumerable: true, get: function () { return teamInviteFunctions_1.createTeamMemberInvitationCode; } });
Object.defineProperty(exports, "validateTeamMemberInvitationCode", { enumerable: true, get: function () { return teamInviteFunctions_1.validateTeamMemberInvitationCode; } });
Object.defineProperty(exports, "revokeTeamMemberInvitationCode", { enumerable: true, get: function () { return teamInviteFunctions_1.revokeTeamMemberInvitationCode; } });
Object.defineProperty(exports, "redeemTeamMemberInvitationCode", { enumerable: true, get: function () { return teamInviteFunctions_1.redeemTeamMemberInvitationCode; } });
var tenantInviteFunctions_1 = require("./tenantInviteFunctions");
Object.defineProperty(exports, "validateTenantInvitationCode", { enumerable: true, get: function () { return tenantInviteFunctions_1.validateTenantInvitationCode; } });
Object.defineProperty(exports, "createTenantInvitationCode", { enumerable: true, get: function () { return tenantInviteFunctions_1.createTenantInvitationCode; } });
Object.defineProperty(exports, "revokeTenantInvitationCode", { enumerable: true, get: function () { return tenantInviteFunctions_1.revokeTenantInvitationCode; } });
Object.defineProperty(exports, "redeemTenantInvitationCode", { enumerable: true, get: function () { return tenantInviteFunctions_1.redeemTenantInvitationCode; } });
Object.defineProperty(exports, "syncTenantAccessFromInvites", { enumerable: true, get: function () { return tenantInviteFunctions_1.syncTenantAccessFromInvites; } });
var adminPortal_1 = require("./adminPortal");
Object.defineProperty(exports, "adminPortalLogin", { enumerable: true, get: function () { return adminPortal_1.adminPortalLogin; } });
Object.defineProperty(exports, "validateAdminPortalSession", { enumerable: true, get: function () { return adminPortal_1.validateAdminPortalSession; } });
Object.defineProperty(exports, "adminPortalLogout", { enumerable: true, get: function () { return adminPortal_1.adminPortalLogout; } });
Object.defineProperty(exports, "adminPortalResetPassword", { enumerable: true, get: function () { return adminPortal_1.adminPortalResetPassword; } });
Object.defineProperty(exports, "listFeedbackAdminTickets", { enumerable: true, get: function () { return adminPortal_1.listFeedbackAdminTickets; } });
Object.defineProperty(exports, "listAdminPortalUsers", { enumerable: true, get: function () { return adminPortal_1.listAdminPortalUsers; } });
Object.defineProperty(exports, "listAdminPortalAuditLogs", { enumerable: true, get: function () { return adminPortal_1.listAdminPortalAuditLogs; } });
Object.defineProperty(exports, "getAdminPortalUserTroubleshootingDetails", { enumerable: true, get: function () { return adminPortal_1.getAdminPortalUserTroubleshootingDetails; } });
Object.defineProperty(exports, "adminPortalPreviewEntitlementGrant", { enumerable: true, get: function () { return adminPortal_1.adminPortalPreviewEntitlementGrant; } });
Object.defineProperty(exports, "adminPortalMutateEntitlementGrant", { enumerable: true, get: function () { return adminPortal_1.adminPortalMutateEntitlementGrant; } });
Object.defineProperty(exports, "adminPortalManageUserSubscription", { enumerable: true, get: function () { return adminPortal_1.adminPortalManageUserSubscription; } });
Object.defineProperty(exports, "adminPortalRefreshUserSubscriptionFromStripe", { enumerable: true, get: function () { return adminPortal_1.adminPortalRefreshUserSubscriptionFromStripe; } });
Object.defineProperty(exports, "adminPortalApplyUserBillingActions", { enumerable: true, get: function () { return adminPortal_1.adminPortalApplyUserBillingActions; } });
Object.defineProperty(exports, "adminPortalCreateComplimentaryAccessCode", { enumerable: true, get: function () { return adminPortal_1.adminPortalCreateComplimentaryAccessCode; } });
Object.defineProperty(exports, "adminPortalListComplimentaryAccessCodes", { enumerable: true, get: function () { return adminPortal_1.adminPortalListComplimentaryAccessCodes; } });
Object.defineProperty(exports, "adminPortalCreateBillingCoupon", { enumerable: true, get: function () { return adminPortal_1.adminPortalCreateBillingCoupon; } });
Object.defineProperty(exports, "adminPortalListBillingCoupons", { enumerable: true, get: function () { return adminPortal_1.adminPortalListBillingCoupons; } });
Object.defineProperty(exports, "adminPortalCreateCheckoutLinkWithCoupon", { enumerable: true, get: function () { return adminPortal_1.adminPortalCreateCheckoutLinkWithCoupon; } });
Object.defineProperty(exports, "updateFeedbackAdminTicketStatus", { enumerable: true, get: function () { return adminPortal_1.updateFeedbackAdminTicketStatus; } });
Object.defineProperty(exports, "linkFeedbackAdminTickets", { enumerable: true, get: function () { return adminPortal_1.linkFeedbackAdminTickets; } });
Object.defineProperty(exports, "unlinkFeedbackAdminTicket", { enumerable: true, get: function () { return adminPortal_1.unlinkFeedbackAdminTicket; } });
Object.defineProperty(exports, "deleteFeedbackAdminParentTicket", { enumerable: true, get: function () { return adminPortal_1.deleteFeedbackAdminParentTicket; } });
var cleanupClosedFeedbackAttachments_1 = require("./cleanupClosedFeedbackAttachments");
Object.defineProperty(exports, "cleanupClosedFeedbackAttachments", { enumerable: true, get: function () { return cleanupClosedFeedbackAttachments_1.cleanupClosedFeedbackAttachments; } });
var maintleyTeamAdmin_1 = require("./maintleyTeamAdmin");
Object.defineProperty(exports, "adminPortalListMaintleyTeam", { enumerable: true, get: function () { return maintleyTeamAdmin_1.adminPortalListMaintleyTeam; } });
Object.defineProperty(exports, "adminPortalMutateMaintleyTeam", { enumerable: true, get: function () { return maintleyTeamAdmin_1.adminPortalMutateMaintleyTeam; } });
var personalAssistantCredentials_1 = require("./personalAssistantCredentials");
Object.defineProperty(exports, "managePersonalAssistantCredentials", { enumerable: true, get: function () { return personalAssistantCredentials_1.managePersonalAssistantCredentials; } });
var personalAssistantApi_1 = require("./personalAssistantApi");
Object.defineProperty(exports, "personalAssistantApi", { enumerable: true, get: function () { return personalAssistantApi_1.personalAssistantApi; } });
var propertyKnowledgeLinks_1 = require("./propertyKnowledgeLinks");
Object.defineProperty(exports, "cleanupEquipmentSpaceLinks", { enumerable: true, get: function () { return propertyKnowledgeLinks_1.cleanupEquipmentSpaceLinks; } });
Object.defineProperty(exports, "cleanupTaskSpaceLinks", { enumerable: true, get: function () { return propertyKnowledgeLinks_1.cleanupTaskSpaceLinks; } });
Object.defineProperty(exports, "removePropertySpace", { enumerable: true, get: function () { return propertyKnowledgeLinks_1.removePropertySpace; } });
Object.defineProperty(exports, "setEquipmentSpaceLinks", { enumerable: true, get: function () { return propertyKnowledgeLinks_1.setEquipmentSpaceLinks; } });
Object.defineProperty(exports, "setTaskSpaceLinks", { enumerable: true, get: function () { return propertyKnowledgeLinks_1.setTaskSpaceLinks; } });
